@ECHO OFF

SET FIND_PYTHON_DEBUG=1
SET FIND_SCONS_DEBUG=1

IF "%FIND_PYTHON_VERSION%"    == "" (SET FIND_PYTHON_VERSION=3.7.0)
IF "%FIND_PYTHON_LOCAL_ROOT%" == "" (SET FIND_PYTHON_LOCAL_ROOT=%~dp0\external)
IF "%FIND_SCONS_VERSION%"     == "" (SET FIND_SCONS_VERSION=3.0.1)
IF "%FIND_SCONS_LOCAL_ROOT%"  == "" (SET FIND_SCONS_LOCAL_ROOT=%~dp0\external)

%~dp0\external\bootstrap-scons\scons.bat %*
