# Get the construction environment from the parent script
Import('env')

objs = []

# ANTLR grammars produce a set of .cpp, .hpp and .txt files. Only the .cpp files need additional compilation.
generated = env.AntlrGrammar(Split("""
    CommonGrammar
    ConfigHACK
    Map
    TerrainLibrary
"""))
objs += env.StaticObject(list(filter((lambda f: f.get_suffix() == '.cpp'), generated)))

objs += env.StaticObject(Split("""
    ConfigParser-functions.cpp
    DEMInterpreter.cpp
    INIParser.cpp
    MapParser-functions.cpp
    TerrainLibraryParser-functions.cpp
    terrainosaurus-iostream.cpp
"""))

Return('objs')
