# Get the construction environment from the parent script
Import('env')

objs = []

# ANTLR grammars produce a set of .cpp, .h and .other files. Only the .cpp files need additional compilation.
generated = env.Antlr4Grammar(Split("""
    Config
    TerrainLibrary
    Map
"""))
objs += env.StaticObject(list(filter((lambda f: f.get_suffix() == '.cpp'), generated)))

objs += env.StaticObject(Split("""
    DEMInterpreter.cpp
    terrainosaurus-iostream.cpp
"""))

Return('objs')
