# Get the construction environment from the parent script
Import('env')

objs = []

# Use a precompiled header on toolchains that support it
env = env.Clone()
pch = env.PCH('precomp.cpp')
env['PCH'] = pch[0]
env['PCHSTOP'] = 'terrainosaurus/precomp.h'
objs += [pch[1]]

objs = env.StaticObject('TerrainosaurusApplication.cpp')
objs += env.SConscript(dirs = ['data', 'io', 'genetics', 'rendering', 'ui'], exports = {'env' : env})

if GetOption('flavor') == 'debug':
    libs = ['antlr4-runtime', 'FreeImaged', 'FreeImagePlusd', 'fftw3f', 'inca']
else:
    libs = ['antlr4-runtime', 'FreeImage', 'FreeImagePlus', 'fftw3f', 'inca']
env.Program('terrainosaurus', objs, LIBS = libs)
